"""Test migration

Revision ID: cecece4ff3bf
Revises: dca0664c5ad5
Create Date: 2022-09-26 17:28:01.880239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecece4ff3bf'
down_revision = 'dca0664c5ad5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("youtube_links") as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_links', 'link',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
