"""Second migration

Revision ID: d6be703c6689
Revises: 
Create Date: 2022-09-26 17:25:07.378533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6be703c6689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("youtube_links") as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_links', 'link',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
